[program:mercado_asturias]
command=/home/erpnext/.services/api_mercadoAsturias/venv/bin/uvicorn app.main:app --host 127.0.0.1 --port 8001 --workers 2
directory=/home/erpnext/.services/api_mercadoAsturias
user=erpnext
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/home/erpnext/.services/api_mercadoAsturias/logs/mercado_asturias.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
environment=PATH="/home/erpnext/.services/api_mercadoAsturias/venv/bin",APP_ENV="production",DATABASE_URL="postgresql://mercado_user:mercado_pass_2026@localhost/mercado_asturias",SECRET_KEY="239a7d08ce2f076c8f39f7f336b7a6b66e627e3ae4c96c84918cf74453ab2a62",ADMIN_USERNAME="admin",ADMIN_PASSWORD="admin320"
